# Feature Scaling

What is Feature

A feature is a measurable property of the object you're trying to analyze

Feature Scaling defined as the method to scale the numeric features in the same scale or range

in this method, we can convert the different scaling data into a single scaling data

This is the last processing after the data pre processing and after this the implementation of ML algorithm takes place.

It is also called as data normalization

It is applied on the independent variables

This is fitted into train data and transform train and test data

Machine Learning cant understand units it only understands numerical values.

1.KNN

2.K-Means

3.Support Vector Machine

4.Principal Component Analysis

5.Linear Discriminant Analysis

# Gradinet Descent Based Algorithms:

Gradient descent is an optimization algorithm which is commonly-used to train machine learning models and neural networks and it is used to optimise the data

1.Linear 

2.Logistic

3.Support Vector Machine

Decision Tree

 Random Forest

XGBoost

1.Min-Max Scalar

2.Standard Scaler

3.Max Abs Scaler

4.Robust Scaler

5.Quantile Transformer Scaler

6.Power Transformer Scaler

7.Unit Vector Scaler

** In which the algorithms used maximumly are Min-Max Scaler and Standard Scaler

# Standardization

Standardisation rescales the feature such as mean=0 and standard deviation(01)=1
(x-mew)/standard deviation

The result of standard deviation is called as Z-score normalization

if the original distribution is normal then the normaldistribution will be normal

if the original distribution is skewed, then the standardization distribution of the varaible will also be skewed.

# Normalization

Normalization rescale the feature in fixed range between 0 and 1

x(norm)=(x-x min)/(x max- xmin)

Normalization is called as Min-Max Scaling

If the data doesn't follow normal distribution(Gaussian Distribution)

# Standardization Vs Normalization

There is no any thumb rule to standaradization or normalization for special ML algorithm

but mostly Standardization use for clustering analyses, Principal Component Analysis.

Normalization prefer for image processing because pixel intensity between 0 to 255, neural network algorithm require data in scale 0-1, K-Nearest Neighbors.

In [1]:
import numpy as np
import pandas as pd

In [2]:
import seaborn as sns

In [3]:
data=sns.load_dataset('titanic')

In [4]:
data

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
data

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [9]:
data1=data[['survived', 'pclass','age', 'parch']]

In [10]:
data1

survived  pclass   age  parch
0           0       3  22.0      0
1           1       1  38.0      0
2           1       3  26.0      0
3           1       1  35.0      0
4           0       3  35.0      0
..        ...     ...   ...    ...
886         0       2  27.0      0
887         1       1  19.0      0
888         0       3   NaN      2
889         1       1  26.0      0
890         0       3  32.0      0

[891 rows x 4 columns]

In [11]:
data2=data1.fillna(data1.mean())

In [67]:
data2.isnull().sum()

survived    0
pclass      0
age         0
parch       0
dtype: int64

In [12]:
data2

survived  pclass        age  parch
0           0       3  22.000000      0
1           1       1  38.000000      0
2           1       3  26.000000      0
3           1       1  35.000000      0
4           0       3  35.000000      0
..        ...     ...        ...    ...
886         0       2  27.000000      0
887         1       1  19.000000      0
888         0       3  29.699118      2
889         1       1  26.000000      0
890         0       3  32.000000      0

[891 rows x 4 columns]

In [13]:
data2.isnull().sum().sum()

0

In [17]:
x=data2.drop('survived', axis=1)

In [18]:
x

pclass        age  parch
0         3  22.000000      0
1         1  38.000000      0
2         3  26.000000      0
3         1  35.000000      0
4         3  35.000000      0
..      ...        ...    ...
886       2  27.000000      0
887       1  19.000000      0
888       3  29.699118      2
889       1  26.000000      0
890       3  32.000000      0

[891 rows x 3 columns]

In [19]:
y=data2['survived']

In [20]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
print('Shape of X=',x.shape)
print('Shape of y=', y.shape)

Shape of X= (891, 3)
Shape of y= (891,)


In [23]:
x_train, x_test, y_train, y_test=train_test_split(x, y , test_size=0.2, random_state=51)

In [25]:
print('Shape of x_train=', x_train.shape)
print('Shape of x_test=', x_test.shape)
print('Shape of y_train=', y_train.shape)
print('Shape of y_test=',y_test.shape)

Shape of x_train= (712, 3)
Shape of x_test= (179, 3)
Shape of y_train= (712,)
Shape of y_test= (179,)


In [29]:
#usind standscalar
from sklearn.preprocessing import StandardScaler

In [30]:
from sklearn.preprocessing import MinMaxScaler

In [66]:
sc=StandardScaler()
sc.fit(x_train)

StandardScaler()

In [32]:
sc.fit

<bound method StandardScaler.fit of StandardScaler()>

In [34]:
 sc.mean_

array([ 2.30617978, 29.55409121,  0.39185393])

In [35]:
sc.scale_

array([ 0.84405789, 12.99162985,  0.79647463])

In [37]:
x_train.describe()

pclass         age       parch
count  712.000000  712.000000  712.000000
mean     2.306180   29.554091    0.391854
std      0.844651   13.000763    0.797035
min      1.000000    0.420000    0.000000
25%      1.750000   22.000000    0.000000
50%      3.000000   29.699118    0.000000
75%      3.000000   35.000000    0.000000
max      3.000000   71.000000    5.000000

In [57]:
#whatever we got the result that we need to convert it into the datasets
x_train=sc.transform(x_train)
x_test=sc.transform(x_test)

In [60]:
x_train

array([[-4.8154985 , -2.45249093, -1.88523673],
       [-4.8154985 , -2.43812546, -1.88523673],
       [-4.8154985 , -2.45841953, -1.88523673],
       ...,
       [-4.8154985 , -2.44154581,  4.05228766],
       [-4.8154985 , -2.44989186,  0.09393806],
       [-4.8154985 , -2.45043872, -1.88523673]])

In [61]:
x_test

array([[-8.14142996, -2.44519418, -1.88523673],
       [-4.8154985 , -2.44884255, -1.88523673],
       [-4.8154985 , -2.44975465, -1.88523673],
       [-8.14142996, -2.44989186, -1.88523673],
       [-6.47846423, -2.44793046,  0.09393806],
       [-4.8154985 , -2.44884255, -1.88523673],
       [-8.14142996, -2.44200186, -1.88523673],
       [-4.8154985 , -2.4561393 , -1.88523673],
       [-6.47846423, -2.43333698, -1.88523673],
       [-8.14142996, -2.45659534,  0.09393806],
       [-6.47846423, -2.4492986 , -1.88523673],
       [-6.47846423, -2.45066674, -1.88523673],
       [-8.14142996, -2.44291395, -1.88523673],
       [-4.8154985 , -2.45294697, -1.88523673],
       [-4.8154985 , -2.44473814,  8.01063725],
       [-6.47846423, -2.45203488, -1.88523673],
       [-6.47846423, -2.44701837,  2.07311286],
       [-4.8154985 , -2.44989186, -1.88523673],
       [-4.8154985 , -2.44989186, -1.88523673],
       [-6.47846423, -2.45477116, -1.88523673],
       [-4.8154985 , -2.44989186, -1.885

In [62]:
x_train=pd.DataFrame(x_train,columns=['pclass', 'age', 'parch'])

In [63]:
x_train

pclass       age     parch
0   -4.815498 -2.452491 -1.885237
1   -4.815498 -2.438125 -1.885237
2   -4.815498 -2.458420 -1.885237
3   -4.815498 -2.455227 -1.885237
4   -4.815498 -2.449892  2.073113
..        ...       ...       ...
707 -4.815498 -2.445650 -1.885237
708 -4.815498 -2.449892  0.093938
709 -4.815498 -2.441546  4.052288
710 -4.815498 -2.449892  0.093938
711 -4.815498 -2.450439 -1.885237

[712 rows x 3 columns]

In [64]:
x_train.describe()

pclass         age       parch
count  712.000000  712.000000  712.000000
mean    -5.969298   -2.449958   -1.109689
std      1.404626    0.005929    1.577471
min     -8.141430   -2.463245   -1.885237
25%     -6.894206   -2.453403   -1.885237
50%     -4.815498   -2.449892   -1.885237
75%     -4.815498   -2.447474   -1.885237
max     -4.815498   -2.431057    8.010637

In [65]:
x_train.describe().round(2)

pclass     age   parch
count  712.00  712.00  712.00
mean    -5.97   -2.45   -1.11
std      1.40    0.01    1.58
min     -8.14   -2.46   -1.89
25%     -6.89   -2.45   -1.89
50%     -4.82   -2.45   -1.89
75%     -4.82   -2.45   -1.89
max     -4.82   -2.43    8.01

In [50]:
x_test=pd.DataFrame(x_test_sc,columns=['pclass', 'age', 'parch'])

In [51]:
x_test

pclass       age     parch
0   -4.565658 -2.212967 -1.109689
1   -1.758380 -2.260365 -1.109689
2   -1.758380 -2.272214 -1.109689
3   -4.565658 -2.273997 -1.109689
4   -3.162019 -2.248515  0.466673
..        ...       ...       ...
174 -1.758380 -2.273997  2.043036
175 -1.758380 -2.295914 -1.109689
176 -3.162019 -2.307763 -1.109689
177 -4.565658 -2.266290 -1.109689
178 -4.565658 -2.230741 -1.109689

[179 rows x 3 columns]