In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df=sns.load_dataset('titanic')

In [3]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [4]:
data=df[['survived','pclass','age', 'parch']]

In [5]:
data

survived  pclass   age  parch
0           0       3  22.0      0
1           1       1  38.0      0
2           1       3  26.0      0
3           1       1  35.0      0
4           0       3  35.0      0
..        ...     ...   ...    ...
886         0       2  27.0      0
887         1       1  19.0      0
888         0       3   NaN      2
889         1       1  26.0      0
890         0       3  32.0      0

[891 rows x 4 columns]

In [6]:
data.isnull().sum()

survived      0
pclass        0
age         177
parch         0
dtype: int64

In [7]:
data.mean()

survived     0.383838
pclass       2.308642
age         29.699118
parch        0.381594
dtype: float64

In [8]:
data2=data.fillna(data.mean())

In [9]:
data2.isnull().sum()

survived    0
pclass      0
age         0
parch       0
dtype: int64

In [10]:
data2

survived  pclass        age  parch
0           0       3  22.000000      0
1           1       1  38.000000      0
2           1       3  26.000000      0
3           1       1  35.000000      0
4           0       3  35.000000      0
..        ...     ...        ...    ...
886         0       2  27.000000      0
887         1       1  19.000000      0
888         0       3  29.699118      2
889         1       1  26.000000      0
890         0       3  32.000000      0

[891 rows x 4 columns]

In [11]:
data2.isnull().sum()

survived    0
pclass      0
age         0
parch       0
dtype: int64

In [12]:
x=data2.drop('survived', axis=1)

In [13]:
x

pclass        age  parch
0         3  22.000000      0
1         1  38.000000      0
2         3  26.000000      0
3         1  35.000000      0
4         3  35.000000      0
..      ...        ...    ...
886       2  27.000000      0
887       1  19.000000      0
888       3  29.699118      2
889       1  26.000000      0
890       3  32.000000      0

[891 rows x 3 columns]

In [14]:
y=data['survived']

In [15]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
x_train, x_test,y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=51)

In [44]:
print('Shape of x_train=', x_train.shape)
print('Shape of x_test=', x_test.shape)
print('Shape of y_train=', y_train.shape)
print('Shape of x_test=', y_test.shape)


Shape of x_train= (712, 3)
Shape of x_test= (179, 3)
Shape of y_train= (712,)
Shape of x_test= (179,)


In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
sc=StandardScaler()

In [47]:
sc.fit(x_train)

StandardScaler()

In [48]:
sc.mean_

array([ 2.30617978, 29.55409121,  0.39185393])

In [49]:
sc.scale_

array([ 0.84405789, 12.99162985,  0.79647463])

In [24]:
x_train.describe()

pclass         age       parch
count  712.000000  712.000000  712.000000
mean     2.306180   29.554091    0.391854
std      0.844651   13.000763    0.797035
min      1.000000    0.420000    0.000000
25%      1.750000   22.000000    0.000000
50%      3.000000   29.699118    0.000000
75%      3.000000   35.000000    0.000000
max      3.000000   71.000000    5.000000

In [25]:
x_test.describe()

pclass         age       parch
count  179.000000  179.000000  179.000000
mean     2.318436   30.275983    0.340782
std      0.803256   13.027411    0.842056
min      1.000000    0.830000    0.000000
25%      2.000000   23.500000    0.000000
50%      3.000000   29.699118    0.000000
75%      3.000000   35.000000    0.000000
max      3.000000   80.000000    6.000000

In [26]:
x_train=sc.transform(x_train)

In [27]:
x_test=sc.transform(x_test)

In [28]:
x_train

array([[ 0.8220055 , -0.42751304, -0.49198545],
       [ 0.8220055 ,  1.997125  , -0.49198545],
       [ 0.8220055 , -1.42815732, -0.49198545],
       ...,
       [ 0.8220055 ,  1.41983023,  3.27461284],
       [ 0.8220055 ,  0.01116307,  0.76354731],
       [ 0.8220055 , -0.08113618, -0.49198545]])

In [29]:
x_test

array([[-1.54750023,  0.80404914, -0.49198545],
       [ 0.8220055 ,  0.18826805, -0.49198545],
       [ 0.8220055 ,  0.03432278, -0.49198545],
       [-1.54750023,  0.01116307, -0.49198545],
       [-0.36274737,  0.34221332,  0.76354731],
       [ 0.8220055 ,  0.18826805, -0.49198545],
       [-1.54750023,  1.34285759, -0.49198545],
       [ 0.8220055 , -1.04329413, -0.49198545],
       [-0.36274737,  2.80533768, -0.49198545],
       [-1.54750023, -1.12026677,  0.76354731],
       [-0.36274737,  0.11129541, -0.49198545],
       [-0.36274737, -0.1196225 , -0.49198545],
       [-1.54750023,  1.18891232, -0.49198545],
       [ 0.8220055 , -0.50448568, -0.49198545],
       [ 0.8220055 ,  0.88102177,  5.78567837],
       [-0.36274737, -0.35054041, -0.49198545],
       [-0.36274737,  0.49615859,  2.01908008],
       [ 0.8220055 ,  0.01116307, -0.49198545],
       [ 0.8220055 ,  0.01116307, -0.49198545],
       [-0.36274737, -0.81237622, -0.49198545],
       [ 0.8220055 ,  0.01116307, -0.491

In [30]:
import pandas as pd
x_train_df=pd.DataFrame(x_train, columns=['pclass', 'age', 'parch'])
x_test_df=pd.DataFrame(x_test, columns=['pclass', 'age', 'parch'])

In [31]:
x_train_df


pclass       age     parch
0    0.822005 -0.427513 -0.491985
1    0.822005  1.997125 -0.491985
2    0.822005 -1.428157 -0.491985
3    0.822005 -0.889349 -0.491985
4    0.822005  0.011163  2.019080
..        ...       ...       ...
707  0.822005  0.727077 -0.491985
708  0.822005  0.011163  0.763547
709  0.822005  1.419830  3.274613
710  0.822005  0.011163  0.763547
711  0.822005 -0.081136 -0.491985

[712 rows x 3 columns]

In [32]:
x_test_df

pclass       age     parch
0   -1.547500  0.804049 -0.491985
1    0.822005  0.188268 -0.491985
2    0.822005  0.034323 -0.491985
3   -1.547500  0.011163 -0.491985
4   -0.362747  0.342213  0.763547
..        ...       ...       ...
174  0.822005  0.011163  2.019080
175  0.822005 -0.273568 -0.491985
176 -0.362747 -0.427513 -0.491985
177 -1.547500  0.111295 -0.491985
178 -1.547500  0.573131 -0.491985

[179 rows x 3 columns]

In [33]:
x_train_df.describe()

pclass           age         parch
count  7.120000e+02  7.120000e+02  7.120000e+02
mean   5.270441e-17  1.515642e-16  2.440308e-17
std    1.000703e+00  1.000703e+00  1.000703e+00
min   -1.547500e+00 -2.242528e+00 -4.919855e-01
25%   -6.589356e-01 -5.814583e-01 -4.919855e-01
50%    8.220055e-01  1.116307e-02 -4.919855e-01
75%    8.220055e-01  4.191860e-01 -4.919855e-01
max    8.220055e-01  3.190201e+00  5.785678e+00

In [34]:
x_train_df.describe().round(2)

pclass     age   parch
count  712.00  712.00  712.00
mean     0.00    0.00    0.00
std      1.00    1.00    1.00
min     -1.55   -2.24   -0.49
25%     -0.66   -0.58   -0.49
50%      0.82    0.01   -0.49
75%      0.82    0.42   -0.49
max      0.82    3.19    5.79

In [35]:
x_test_df.describe()

pclass         age       parch
count  179.000000  179.000000  179.000000
mean     0.014520    0.055566   -0.064122
std      0.951660    1.002754    1.057229
min     -1.547500   -2.210969   -0.491985
25%     -0.362747   -0.465999   -0.491985
50%      0.822005    0.011163   -0.491985
75%      0.822005    0.419186   -0.491985
max      0.822005    3.882955    7.041211

In [36]:
from sklearn.preprocessing import MinMaxScaler

In [37]:
mms=MinMaxScaler()
mms.fit(x_train)

MinMaxScaler()

In [38]:
x_train

array([[ 0.8220055 , -0.42751304, -0.49198545],
       [ 0.8220055 ,  1.997125  , -0.49198545],
       [ 0.8220055 , -1.42815732, -0.49198545],
       ...,
       [ 0.8220055 ,  1.41983023,  3.27461284],
       [ 0.8220055 ,  0.01116307,  0.76354731],
       [ 0.8220055 , -0.08113618, -0.49198545]])

In [39]:
x_train_ms=mms.transform(x_train)
x_test_ms=mms.transform(x_test)


In [40]:
x_train_ms

array([[1.        , 0.33408898, 0.        ],
       [1.        , 0.78039105, 0.        ],
       [1.        , 0.14990082, 0.        ],
       ...,
       [1.        , 0.67412865, 0.6       ],
       [1.        , 0.4148359 , 0.2       ],
       [1.        , 0.39784642, 0.        ]])

In [41]:
x_test_ms

array([[0.        , 0.56078209, 0.        ],
       [1.        , 0.44743553, 0.        ],
       [1.        , 0.41909889, 0.        ],
       [0.        , 0.4148359 , 0.        ],
       [0.5       , 0.47577217, 0.2       ],
       [1.        , 0.44743553, 0.        ],
       [0.        , 0.65996033, 0.        ],
       [1.        , 0.22074242, 0.        ],
       [0.5       , 0.9291584 , 0.        ],
       [0.        , 0.2065741 , 0.2       ],
       [0.5       , 0.43326721, 0.        ],
       [0.5       , 0.39076226, 0.        ],
       [0.        , 0.63162369, 0.        ],
       [1.        , 0.31992066, 0.        ],
       [1.        , 0.57495041, 1.        ],
       [0.5       , 0.3482573 , 0.        ],
       [0.5       , 0.50410881, 0.4       ],
       [1.        , 0.4148359 , 0.        ],
       [1.        , 0.4148359 , 0.        ],
       [0.5       , 0.26324738, 0.        ],
       [1.        , 0.4148359 , 0.        ],
       [0.5       , 0.24907906, 0.        ],
       [1.