In [1]:
import numpy as np
import pandas as pd

In [5]:
from sklearn.datasets import load_breast_cancer
data=load_breast_cancer()

In [6]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [8]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [9]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [10]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [13]:
df = pd.DataFrame(np.c_[data.data, data.target], columns=[list(data.feature_names)+['target']])
df.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760         0.3001             0.14710        0.2419   
1          0.07864         0.0869             0.07017        0.1812   
2          0.15990         0.1974             0.12790        0.2069   
3          0.28390         0.2414             0.10520        0.2597   
4          0.13280         0.1980             0.10430        0.1809   

  mean fractal dimension  ... worst texture worst perimeter worst area  \
0                0.07871  ...         17.33          184.60     2019.0   
1                0.05667  ...         23.41          158.80     1956.0   
2                0.05999  ...         25.53          152.50     1709.0   
3                0.09744  ...         26.50           98.87      567.7   
4                0.05883  ...         16.67          152.20     1575.0   

  worst smoothness worst compactness worst concavity worst concave points  \
0           0.1622            0.6656          0.7119               0.2654   
1           0.1238            0.1866          0.2416               0.1860   
2           0.1444            0.4245          0.4504               0.2430   
3           0.2098            0.8663          0.6869               0.2575   
4           0.1374            0.2050          0.4000               0.1625   

  worst symmetry worst fractal dimension target  
0         0.4601                 0.11890    0.0  
1         0.2750                 0.08902    0.0  
2         0.3613                 0.08758    0.0  
3         0.6638                 0.17300    0.0  
4         0.2364                 0.07678    0.0  

[5 rows x 31 columns]

In [14]:
df.shape

(569, 31)

In [15]:
X = df.iloc[:, 0:-1]
y = df.iloc[:, -1]

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test,y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=2020)
print('Shape of X_train=', X_train.shape)
print('Shape of X_test=', X_test.shape)
print('Shape of y_train=',y_test.shape)
print('Shape of y_test=', y_test.shape)

Shape of X_train= (455, 30)
Shape of X_test= (114, 30)
Shape of y_train= (114,)
Shape of y_test= (114,)


# Support Vector Classification Model


In [19]:
from sklearn.svm import SVC

In [30]:
classi=SVC(kernel='rbf')


In [31]:
classi.fit(X_train, y_train)

C:\Users\Suman\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


SVC()

In [41]:
classi.score(X_test, y_test)*100

C:\Users\Suman\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


42.10526315789473

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
sc=StandardScaler()

In [35]:
sc.fit(X_train, y_train)

C:\Users\Suman\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


StandardScaler()

In [36]:
X_traind=sc.transform(X_train)
X_testd=sc.transform(X_test)

C:\Users\Suman\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\Suman\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


In [37]:
classi.fit(X_traind, y_train)

SVC()

In [40]:
classi.score(X_testd, y_test)*100

95.6140350877193

In [43]:
poly=SVC(kernel='poly',degree=2)


In [44]:
poly.fit(X_traind, y_train)

SVC(degree=2, kernel='poly')

In [45]:
poly.score(X_testd, y_test)

0.8333333333333334

In [46]:
line=SVC(kernel='linear')

In [47]:
line.fit(X_traind, y_train)
line.score(X_testd, y_test)

0.9649122807017544

In [51]:
patient1=df[0,:]

InvalidIndexError: (0, slice(None, None, None))

In [53]:
X_test.shape

(114, 30)

In [54]:
X_test

mean radius mean texture mean perimeter mean area mean smoothness  \
236       23.21        26.97         153.50    1670.0         0.09509   
106       11.64        18.33          75.17     412.5         0.11420   
284       12.89        15.70          84.08     516.6         0.07818   
262       17.29        22.13         114.40     947.8         0.08999   
356       13.05        18.59          85.09     512.0         0.10820   
..          ...          ...            ...       ...             ...   
370       16.35        23.29         109.00     840.4         0.09742   
167       16.78        18.80         109.30     886.3         0.08865   
108       22.27        19.67         152.80    1509.0         0.13260   
131       15.46        19.48         101.70     748.9         0.10920   
336       12.99        14.23          84.08     514.3         0.09462   

    mean compactness mean concavity mean concave points mean symmetry  \
236          0.16820        0.19500             0.12370        0.1909   
106          0.10170        0.07070             0.03485        0.1801   
284          0.09580        0.11150             0.03390        0.1432   
262          0.12730        0.09697             0.07507        0.2108   
356          0.13040        0.09603             0.05603        0.2035   
..               ...            ...                 ...           ...   
370          0.14970        0.18110             0.08773        0.2175   
167          0.09182        0.08422             0.06576        0.1893   
108          0.27680        0.42640             0.18230        0.2556   
131          0.12230        0.14660             0.08087        0.1931   
336          0.09965        0.03738             0.02098        0.1652   

    mean fractal dimension  ... worst radius worst texture worst perimeter  \
236                0.06309  ...        31.01         34.51          206.00   
106                0.06520  ...        13.14         29.26           85.51   
284                0.05935  ...        13.90         19.69           92.12   
262                0.05464  ...        20.39         27.24          137.90   
356                0.06501  ...        14.19         24.85           94.22   
..                     ...  ...          ...           ...             ...   
370                0.06218  ...        19.38         31.03          129.30   
167                0.05534  ...        20.05         26.30          130.70   
108                0.07039  ...        28.40         28.01          206.80   
131                0.05796  ...        19.26         26.00          124.90   
336                0.07238  ...        13.72         16.91           87.38   

    worst area worst smoothness worst compactness worst concavity  \
236     2944.0          0.14810            0.4126          0.5820   
106      521.7          0.16880            0.2660          0.2873   
284      595.6          0.09926            0.2317          0.3344   
262     1295.0          0.11340            0.2867          0.2298   
356      591.2          0.13430            0.2658          0.2573   
..         ...              ...               ...             ...   
370     1165.0          0.14150            0.4665          0.7087   
167     1260.0          0.11680            0.2119          0.2318   
108     2360.0          0.17010            0.6997          0.9608   
131     1156.0          0.15460            0.2394          0.3791   
336      576.0          0.11420            0.1975          0.1450   

    worst concave points worst symmetry worst fractal dimension  
236               0.2593         0.3103                 0.08677  
106               0.1218         0.2806                 0.09097  
284               0.1017         0.1999                 0.07127  
262               0.1528         0.3067                 0.07484  
356               0.1258         0.3113                 0.08317  
..                   ...            ...                     ...  
370               0.22

In [57]:
patient1 = [17.99,
 10.38,
 122.8,
 1001.0,
 0.1184,
 0.2776,
 0.3001,
 0.1471,
 0.2419,
 0.07871,
 1.095,
 0.9053,
 8.589,
 153.4,
 0.006399,
 0.04904,
 0.05373,
 0.01587,
 0.03003,
 0.006193,
 25.38,
 17.33,
 184.6,
 2019.0,
 0.1622,
 0.6656,
 0.7119,
 0.2654,
 0.4601,
 0.1189]

In [59]:
patientsc=sc.transform(np.array([patient1]))

In [60]:
patientsc

array([[ 1.14157516, -2.04268291,  1.31822055,  1.02590938,  1.62044096,
         3.42348005,  2.74540674,  2.64970572,  2.34762157,  2.34157979,
         2.47642647, -0.56729422,  2.77495792,  2.4478528 , -0.23516697,
         1.35781809,  0.68489284,  0.64085494,  1.1927004 ,  0.93126314,
         1.94777877, -1.35487239,  2.37210178,  2.06352534,  1.31020065,
         2.82342306,  2.23450433,  2.38372721,  2.86683913,  2.10454451]])

In [64]:
line.predict(patientsc)

array([0.])